name: Action self-test
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: pyenv-action self-test
    steps:
    - name: Enable pyenv in build
      id: pyenv
      uses: "gabrielfalcao/pyenv-action@${{ github.sha }}"
      with:
        default: 3.7.3
        command: |
          pip install -U pip
          pip install -U setuptools

        versions: 3.6.5,3.7.2

    # Use the output from the `hello` step
    - name: List python versions
      run: pyenv versions

    - name: Verify python 3.6.5 installation
      run: pyenv local 3.6.5 && python --version

    - name: Verify python 3.6.5 installation
      run: pyenv local 3.6.5 && python --version
